name: nosferatu
channels:
  - conda-forge
dependencies:
  - numpy>=2.2.2
  - pandas>=2.2.3
  - scikit-learn>=1.6.1
  - pytest>=8.3.4
  - _libgcc_mutex>=0.1
  - _openmp_mutex>=4.5
  - _r-mutex>=1.0.1
  - anyio>=4.6.2
  - argon2-cffi>=21.3.0
  - argon2-cffi-bindings>=21.2.0
  - astroid>=3.3.8
  - asttokens>=2.0.5
  - async-lru>=2.0.4
  - attrs>=24.3.0
  - autopep8>=2.0.4
  - babel>=2.16.0
  - beautifulsoup4>=4.12.3
  - binutils_impl_linux-64>=2.40
  - binutils_linux-64>=2.40.0
  - blas>=1.1
  - bleach>=6.2.0
  - bottleneck>=1.4.2
  - brotli>=1.0.9
  - brotli-bin>=1.0.9
  - brotli-python>=1.0.9
  - bwidget>=1.10.1
  - bzip2>=1.0.8
  - c-ares>=1.19.1
  - ca-certificates>=2025.2.25
  - cairo>=1.16.0
  - certifi>=2025.1.31
  - cffi>=1.17.1
  - charset-normalizer>=3.3.2
  - colorama>=0.4.6
  - comm>=0.2.1
  - contourpy>=1.3.1
  - curl>=8.11.1
  - cycler>=0.11.0
  - cyrus-sasl>=2.1.28
  - dbus>=1.13.18
  - debugpy>=1.8.11
  - decorator>=5.1.1
  - defusedxml>=0.7.1
  - dill>=0.3.9
  - docstring-to-markdown>=0.15
  - executing>=0.8.3
  - expat>=2.6.4
  - flake8>=7.1.1
  - font-ttf-dejavu-sans-mono>=2.37
  - font-ttf-inconsolata>=3.000
  - font-ttf-source-code-pro>=2.038
  - font-ttf-ubuntu>=0.83
  - fontconfig>=2.14.1
  - fonts-conda-ecosystem>=1
  - fonts-conda-forge>=1
  - fonttools>=4.55.3
  - freetype>=2.12.1
  - fribidi>=1.0.10
  - gcc_impl_linux-64>=11.2.0
  - gcc_linux-64>=11.2.0
  - gfortran_impl_linux-64>=11.2.0
  - gfortran_linux-64>=11.2.0
  - glib>=2.78.4
  - glib-tools>=2.78.4
  - graphite2>=1.3.14
  - gst-plugins-base>=1.14.1
  - gstreamer>=1.14.1
  - gxx_impl_linux-64>=11.2.0
  - gxx_linux-64>=11.2.0
  - h11>=0.14.0
  - harfbuzz>=4.3.0
  - httpcore>=1.0.2
  - httpx>=0.27.0
  - icu>=73.1
  - idna>=3.7
  - importlib-metadata>=8.5.0
  - ipykernel>=6.29.5
  - ipython>=8.30.0
  - ipywidgets>=8.1.5
  - isort>=5.13.2
  - jedi>=0.19.2
  - jinja2>=3.1.6
  - jpeg>=9e
  - json5>=0.9.25
  - jsonschema>=4.23.0
  - jsonschema-specifications>=2023.7.1
  - jupyter>=1.1.1
  - jupyter-lsp>=2.2.0
  - jupyter_client>=8.6.3
  - jupyter_console>=6.6.3
  - jupyter_core>=5.7.2
  - jupyter_events>=0.12.0
  - jupyter_server>=2.15.0
  - jupyter_server_terminals>=0.4.4
  - jupyterlab>=4.3.4
  - jupyterlab_pygments>=0.1.2
  - jupyterlab_server>=2.27.3
  - jupyterlab_widgets>=3.0.13
  - kernel-headers_linux-64>=3.10.0
  - kiwisolver>=1.4.8
  - krb5>=1.20.1
  - lcms2>=2.16
  - ld_impl_linux-64>=2.40
  - lerc>=4.0.0
  - libabseil>=20240116.2
  - libbrotlicommon>=1.0.9
  - libbrotlidec>=1.0.9
  - libbrotlienc>=1.0.9
  - libclang>=14.0.6
  - libclang13>=14.0.6
  - libcups>=2.4.2
  - libcurl>=8.11.1
  - libdeflate>=1.22
  - libedit>=3.1.20230828
  - libev>=4.33
  - libffi>=3.4.4
  - libgcc>=14.2.0
  - libgcc-devel_linux-64>=11.2.0
  - libgcc-ng>=14.2.0
  - libgfortran>=14.2.0
  - libgfortran-ng>=14.2.0
  - libgfortran5>=14.2.0
  - libglib>=2.78.4
  - libgomp>=14.2.0
  - libiconv>=1.16
  - libllvm14>=14.0.6
  - libnghttp2>=1.57.0
  - libopenblas>=0.3.28
  - libpng>=1.6.39
  - libpq>=17.2
  - libprotobuf>=4.25.3
  - libsodium>=1.0.18
  - libssh2>=1.11.1
  - libstdcxx>=14.2.0
  - libstdcxx-devel_linux-64>=11.2.0
  - libstdcxx-ng>=11.2.0
  - libtiff>=4.5.1
  - libuuid>=1.41.5
  - libwebp-base>=1.5.0
  - libxcb>=1.15
  - libxkbcommon>=1.0.1
  - libxml2>=2.13.5
  - libxslt>=1.1.41
  - lz4-c>=1.9.4
  - make>=4.4.1
  - markupsafe>=3.0.2
  - matplotlib>=3.10.1
  - matplotlib-base>=3.10.1
  - matplotlib-inline>=0.1.6
  - mccabe>=0.7.0
  - minizip>=4.0.3
  - mistune>=3.1.2
  - mysql>=8.4.0
  - nbclient>=0.10.2
  - nbconvert>=7.16.6
  - nbconvert-core>=7.16.6
  - nbconvert-pandoc>=7.16.6
  - nbformat>=5.10.4
  - ncurses>=6.4
  - nest-asyncio>=1.6.0
  - notebook>=7.3.2
  - notebook-shim>=0.2.4
  - nspr>=4.35
  - nss>=3.89.1
  - numexpr>=2.10.1
  - numpy-base>=2.0.1
  - openblas>=0.3.28
  - openjpeg>=2.5.2
  - openldap>=2.6.4
  - openssl>=3.4.0
  - overrides>=7.4.0
  - packaging>=24.2
  - pandoc>=2.12
  - pandocfilters>=1.5.0
  - pango>=1.50.9
  - paramiko>=2.11.0
  - parso>=0.9.0
  - pathos>=0.2.5
  - pexpect>=4.8.0
  - pickleshare>=0.7.5
  - pillow>=9.5.0
  - pip>=23.1.2
  - plotly>=5.10.0
  - psutil>=5.9.5
  - pureeval>=0.2.2
  - py4j>=0.10.10.6
  - pyasn1>=0.5.0
  - pycairo>=1.23.0
  - pycosat>=0.6.3
  - pycparser>=2.21
  - pydantic>=2.6.0
  - pydeck>=0.8.0
  - pydot>=1.5.0
  - pygraphviz>=1.8
  - pyjwt>=2.8.0
  - pyopenssl>=23.1.1
  - pyparsing>=3.0.9
  - pyrsistent>=0.19.3
  - pysocks>=1.7.1
  - pytest>=7.2.2
  - python>=3.11
  - python_abi>=3.11
  - pytorch>=2.1.0
  - pytorch-cuda>=2.1.0
  - pyyaml>=6.0
  - pyzmq>=25.1.0
  - qt>=5.15.9
  - qt5-sqldriver>=5.15.9
  - qtbase>=5.15.9
  - qtcharts>=5.15.9
  - qtconnectivity>=5.15.9
  - qtdoc>=5.15.9
  - qtgraphicaleffects>=5.15.9
  - qtlocation>=5.15.9
  - qtmultimedia>=5.15.9
  - qtscript>=5.15.9
  - qtsensors>=5.15.9
  - qtserialport>=5.15.9
  - qttest>=5.15.9
  - qtwebsockets>=5.15.9
  - qtwebview>=5.15.9
  - r-base>=4.2.2
  - r-biocmanager>=1.30.17
  - r-curl>=5.0.0
  - r-digest>=0.6.31
  - r-ggplot2>=3.4.1
  - r-knitr>=1.41
  - r-matrix>=1.5.3
  - r-rcpp>=1.0.9
  - r-reshape2>=1.4.4
  - r-stringr>=1.5.0
  - r-tidyverse>=2.0.0
  - r-viridis>=0.6.0
  - readline>=8.2
  - regex>=2023.4.23
  - requests>=2.31.0
  - requests-toolbelt>=0.10.1
  - scipy>=1.11.1
  - seaborn>=0.12.2
  - setuptools>=65.5.0
  - sip>=4.19.24
  - six>=1.16.0
  - sniffio>=1.3.0
  - snowballstemmer>=2.2.0
  - sortedcontainers>=2.4.0
  - sphinx>=6.2.2
  - sphinxcontrib-websupport>=1.2.4
  - sqlite>=3.41.2
  - sympy>=1.11.1
  - tbb>=2021.9.0
  - tensorboard>=2.13.0
  - tensorflow>=2.13.0
  - terminado>=0.15.0
  - testpath>=0.6.0
  - tornado>=6.2
  - tqdm>=4.66.0
  - traitlets>=5.9.0
  - typing_extensions>=4.6.3
  - urllib3>=1.26.15
  - vega_datasets>=0.10.1
  - werkzeug>=2.3.6
  - wheel>=0.41.1
  - xz>=5.2.11
  - zlib>=1.2.12
  - zstd>=1.5.5
  - pip:
      - imageio>=2.37.0
      - lazy-loader>=0.4
      - networkx>=3.4.2
      - opencv-python>=4.11.0.86
      - scikit-image>=0.25.0
      - tifffile>=2025.3.13
      - pyqt6
      - opencv-python
