[build-system]
requires = ["setuptools >= 64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nosferatu"
version = "0.1.0"
authors = [
	{ name="Nels Schimek", email="nlsschim@uw.edu"},
	{ name="Krista Phommatha", email="krisphom@uw.edu" },
	{ name="Muna Yase", email="myase@uw.edu"},
	{ name="Heather Wood", email=""},
	{ name="", email=""},
	{ name="", email=""},
]
